### PR TITLE
PR for issue #57

### PR DESCRIPTION
**Pull request by ekollof**
Change hardcoded path to something smarter

### CODE REVIEW

**Comment by abiosoft** [comment]
Hi, thanks for thanks PR.

Kindly change this line as well to fix the build.
https://github.com/abiosoft/caddy-git/blob/master/git_test.go#L223

**Comment by ekollof** [comment]
Whoops, nice find. I'll change that one too

**Comment by ekollof** [comment]
There you go :)

**Comment by abiosoft** [comment]
Thanks :)

**Comment by abiosoft** [comment]
Deployed. New downloads from caddyserver.com should have the latest version.

👍

**Pull request merged**
