### PR TITLE
Add gitlab webhook handler

### PR DESCRIPTION
**Pull request by tarfu**
Hi,

I copied and modified the Github handler in a way it accepts gitlab webhooks as well.

Regards,

Tobias

### CODE REVIEW

**Comment by abiosoft** [comment]
Thanks for this.

**Comment by tarfu** [comment]
not a good idea to merge it that fast ... forgot to push the second commit ...

**Comment by abiosoft** [comment]
Its my fault for not setting up CI previously. The build failed with the following error after merging your PR. Kindly fix and send a new PR. 

```
./gitlab_hook.go:40: cannot use r.Body (type io.ReadCloser) as type []byte in argument to g.handlePush
```

Thanks.

**Comment by abiosoft** [comment]
I have reverted it already.

**Pull request merged**
